"""
Pydantic models for FitAI API request and response schemas.
"""

import uuid
from typing import Literal, Optional
from pydantic import BaseModel, Field


# ==================== User Profile Models ====================

class UserProfile(BaseModel):
    """User profile data for generating personalized plans."""
    user_id: str = Field(..., description="Unique user identifier")
    age: int = Field(..., ge=13, le=100, description="User's age in years")
    gender: Literal["male", "female"] = Field(..., description="User's gender")
    height: float = Field(..., gt=0, description="Height in cm")
    weight: float = Field(..., gt=0, description="Weight in kg")
    goal: Literal["weight_loss", "muscle_gain", "maintenance", "endurance", "flexibility", "general_fitness"] = Field(
        ..., description="User's fitness goal"
    )
    days_per_week: int = Field(..., ge=1, le=7, description="Days per week available for exercise")
    intensity: Literal["beginner", "intermediate", "advanced"] = Field(
        ..., description="Workout intensity level"
    )
    injuries: Optional[str] = Field(None, description="Any injuries or physical limitations")
    dietary_restrictions: Optional[str] = Field(None, description="Dietary restrictions (e.g., vegetarian, vegan, gluten-free)")


# ==================== Plan Structure Models ====================

class WorkoutDay(BaseModel):
    """Single day workout plan."""
    day: str
    focus: str
    exercises: list[dict]
    duration_minutes: int
    notes: Optional[str] = None


class WorkoutPlan(BaseModel):
    """Complete workout plan."""
    plan_name: str
    description: str
    weekly_schedule: list[WorkoutDay]
    warm_up_routine: list[str]
    cool_down_routine: list[str]
    tips: list[str]


class Meal(BaseModel):
    """Single meal."""
    name: str
    ingredients: list[str]
    calories: int
    protein_g: float
    carbs_g: float
    fat_g: float
    preparation_time_minutes: int
    instructions: Optional[str] = None


class DailyMealPlan(BaseModel):
    """Daily meal plan."""
    day: str
    breakfast: Meal
    lunch: Meal
    dinner: Meal
    snacks: list[Meal]
    total_calories: int
    total_protein_g: float
    total_carbs_g: float
    total_fat_g: float


class MealPlan(BaseModel):
    """Complete meal plan."""
    plan_name: str
    description: str
    daily_calories_target: int
    macros_split: dict
    weekly_meals: list[DailyMealPlan]
    shopping_list: list[str]
    tips: list[str]


# ==================== API Request/Response Models ====================

class PlanResponse(BaseModel):
    """Response model for generated plans."""
    id: str
    user_id: str
    user_profile: UserProfile
    reasoning_analysis: Optional[dict] = Field(None, description="Risk assessment and instructions from reasoning subagent")
    workout_plan: dict
    meal_plan: dict
    created_at: str


class TextProfileRequest(BaseModel):
    """Simple text-based profile input for plan generation."""
    user_id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique user identifier")
    profile: str = Field(..., description="Text description of user profile including demographics, medical history, goals, constraints")


class SimplePlanResponse(BaseModel):
    """Response model for text-based plan generation."""
    id: str
    user_id: str
    profile: str
    task_instructions: str = Field(..., description="Task instructions generated by reasoning agent")
    workout_plan: dict = Field(..., description="Workout plan with summary field")
    meal_plan: dict = Field(..., description="Meal plan with summary field")
    created_at: str


class CorrectionRequest(BaseModel):
    """Request model for plan corrections."""
    user_id: str = Field(..., description="User ID to fetch and correct plans for")
    instruction: str = Field(..., description="Text instruction describing the corrections to make")
    plan_type: Literal["workout", "meal", "both"] = Field(
        default="both", 
        description="Which plan to correct: workout, meal, or both"
    )


class CorrectionResponse(BaseModel):
    """Response model for corrected plans."""
    id: str
    user_id: str
    workout_plan: Optional[dict] = None
    meal_plan: Optional[dict] = None
    correction_applied: str
    updated_at: str


class ReasoningOutput(BaseModel):
    """Output from the reasoning subagent."""
    risk_level: Literal["low", "moderate", "high"] = Field(..., description="Overall risk level")
    risk_factors_identified: list[str] = Field(default_factory=list, description="List of identified risk factors")
    safety_instructions: list[str] = Field(default_factory=list, description="Mandatory safety considerations")
    workout_instructions: list[str] = Field(default_factory=list, description="Specific workout modifications")
    meal_instructions: list[str] = Field(default_factory=list, description="Specific nutrition modifications")
    behavioral_considerations: list[str] = Field(default_factory=list, description="Adherence/motivation factors")
    contraindications: list[str] = Field(default_factory=list, description="Exercises or foods to avoid")
    medical_notes: list[str] = Field(default_factory=list, description="Medical coordination needed")


# ==================== Comprehensive Health Profile Models ====================

class BodyComposition(BaseModel):
    """Body composition measurements."""
    height_cm: float = Field(..., gt=0, description="Height in cm")
    weight_kg: float = Field(..., gt=0, description="Weight in kg")
    bmi: Optional[float] = Field(None, description="BMI (calculated if not provided)")
    body_fat_percent: Optional[float] = Field(None, ge=0, le=100, description="Body fat percentage")
    measurement_method: Optional[str] = Field(None, description="Method used (BIA, DEXA, calipers, etc.)")
    waist_circumference_cm: Optional[float] = Field(None, description="Waist circumference in cm")
    hip_circumference_cm: Optional[float] = Field(None, description="Hip circumference in cm")


class MedicalHistory(BaseModel):
    """Medical history and PAR-Q+ information."""
    # PAR-Q+ Questions
    heart_condition: bool = Field(default=False, description="Has heart condition or takes heart medication")
    chest_pain_activity: bool = Field(default=False, description="Chest pain during physical activity")
    chest_pain_rest: bool = Field(default=False, description="Chest pain at rest in past month")
    balance_consciousness: bool = Field(default=False, description="Loses balance or consciousness")
    bone_joint_condition: bool = Field(default=False, description="Bone/joint problem worsened by exercise")
    blood_pressure_medication: bool = Field(default=False, description="Currently on blood pressure medication")
    other_reason_no_exercise: bool = Field(default=False, description="Any other reason to avoid exercise")
    
    # Diagnoses
    diagnoses: Optional[list[str]] = Field(default=None, description="List of diagnosed conditions (diabetes, PCOS, hypertension, etc.)")
    
    # Medications
    medications: Optional[list[str]] = Field(default=None, description="Current medications")
    
    # Injuries and limitations
    injuries: Optional[list[str]] = Field(default=None, description="Current or past injuries")
    surgeries: Optional[list[str]] = Field(default=None, description="Past surgeries")
    
    # Additional
    physician_clearance: bool = Field(default=False, description="Has physician clearance for exercise")
    notes: Optional[str] = Field(None, description="Additional medical notes")


class PsychologicalFactors(BaseModel):
    """Psychological and behavioral factors."""
    motivation_level: Optional[Literal["low", "moderate", "high"]] = Field(None, description="Current motivation level")
    stress_level: Optional[Literal["low", "moderate", "high"]] = Field(None, description="Current stress level")
    sleep_quality: Optional[Literal["poor", "fair", "good", "excellent"]] = Field(None, description="Sleep quality")
    sleep_hours: Optional[float] = Field(None, ge=0, le=24, description="Average sleep hours per night")
    exercise_history: Optional[Literal["none", "sporadic", "regular", "athletic"]] = Field(None, description="Exercise history")
    previous_program_adherence: Optional[Literal["poor", "moderate", "good"]] = Field(None, description="Adherence to previous programs")
    eating_behaviors: Optional[list[str]] = Field(None, description="Eating patterns (emotional eating, binge eating, etc.)")
    social_support: Optional[Literal["none", "limited", "moderate", "strong"]] = Field(None, description="Social support level")
    barriers: Optional[list[str]] = Field(None, description="Perceived barriers to exercise/diet")


class Constraints(BaseModel):
    """Time, equipment, and environmental constraints."""
    # Time constraints
    minutes_per_session: Optional[int] = Field(None, ge=10, le=180, description="Available minutes per workout session")
    days_per_week: int = Field(..., ge=1, le=7, description="Days available for exercise")
    preferred_workout_time: Optional[Literal["morning", "afternoon", "evening", "flexible"]] = Field(None)
    
    # Equipment access
    equipment_access: Optional[Literal["none", "home_basic", "home_full", "gym"]] = Field(None, description="Equipment availability")
    available_equipment: Optional[list[str]] = Field(None, description="Specific equipment available")
    
    # Environment
    workout_environment: Optional[Literal["home", "gym", "outdoor", "mixed"]] = Field(None)
    climate_considerations: Optional[str] = Field(None, description="Climate/weather constraints")
    
    # Dietary constraints
    dietary_restrictions: Optional[list[str]] = Field(None, description="Dietary restrictions (vegetarian, vegan, allergies, etc.)")
    cooking_skill: Optional[Literal["none", "basic", "intermediate", "advanced"]] = Field(None)
    meal_prep_time: Optional[int] = Field(None, description="Minutes available for meal prep per day")
    budget_constraints: Optional[Literal["tight", "moderate", "flexible"]] = Field(None)


class ComprehensiveProfile(BaseModel):
    """Comprehensive health profile for detailed analysis."""
    user_id: str = Field(..., description="Unique user identifier")
    
    # Demographics
    age: int = Field(..., ge=13, le=100, description="Age in years")
    sex: Literal["male", "female"] = Field(..., description="Biological sex")
    
    # Body Composition
    body_composition: BodyComposition
    
    # Activity Level
    activity_level: Literal["sedentary", "lightly_active", "moderately_active", "very_active", "extremely_active"] = Field(
        ..., description="Current activity level"
    )
    
    # Medical History
    medical_history: MedicalHistory
    
    # Psychological & Behavioral
    psychological_factors: Optional[PsychologicalFactors] = None
    
    # Constraints
    constraints: Constraints
    
    # Goals
    primary_goal: Literal["weight_loss", "muscle_gain", "maintenance", "endurance", "flexibility", "general_fitness", "health_improvement"] = Field(
        ..., description="Primary fitness goal"
    )
    secondary_goals: Optional[list[str]] = Field(None, description="Secondary goals")
    target_weight_kg: Optional[float] = Field(None, description="Target weight in kg")
    timeline_weeks: Optional[int] = Field(None, description="Goal timeline in weeks")


class AnalysisResponse(BaseModel):
    """Response from the profile analysis endpoint."""
    user_id: str
    analysis_id: str
    risk_level: str
    parq_flags: list[str] = Field(default_factory=list, description="PAR-Q+ positive responses requiring attention")
    requires_medical_clearance: bool
    reasoning_analysis: dict
    calculated_metrics: dict
    recommendations_summary: str
    analyzed_at: str


# ==================== Structured Workout Plan Models (for LLM output) ====================

class IntensityPrescription(BaseModel):
    """Intensity prescription for an exercise set."""
    intensity_type_code: str = Field(..., description="Type code: 'rpe', 'percent_1rm', 'hr_zone', etc.")
    intensity_name: Optional[str] = Field(None, description="Human-readable name like 'Rate of Perceived Exertion'")
    target_value: float = Field(..., description="Target intensity value")
    target_value_min: Optional[float] = Field(None, description="Minimum acceptable value")
    target_value_max: Optional[float] = Field(None, description="Maximum acceptable value")
    applies_to_sets: Optional[list[int]] = Field(None, description="Which set numbers this applies to, e.g. [1,2,3,4,5]")
    notes: Optional[str] = Field(None, description="Additional notes like 'Leave 2-3 reps in the tank'")


class SessionExerciseDetails(BaseModel):
    """Details for how an exercise is performed in a specific session."""
    exercise_order: int = Field(..., ge=1, description="Order of exercise in the session")
    sets: int = Field(..., ge=1, description="Number of sets")
    reps: Optional[int] = Field(None, ge=1, description="Number of reps per set (if rep-based)")
    duration_seconds: Optional[int] = Field(None, description="Duration in seconds (if time-based)")
    rest_seconds: int = Field(..., ge=0, description="Rest time between sets in seconds")
    rest_seconds_min: Optional[int] = Field(None, description="Minimum rest time")
    rest_seconds_max: Optional[int] = Field(None, description="Maximum rest time")
    load_type: Optional[str] = Field(None, description="Load prescription type: 'rpe_based', 'percent_1rm', 'bodyweight', etc.")
    tempo: Optional[str] = Field(None, description="Tempo notation like '2-0-1-0' (eccentric-pause-concentric-pause)")
    notes: Optional[str] = Field(None, description="Exercise-specific notes")
    intensity_prescriptions: Optional[list[IntensityPrescription]] = Field(default=None, description="Intensity prescriptions for the exercise")


class SessionExercise(BaseModel):
    """An exercise within a workout session."""
    name: str = Field(..., description="Name of the exercise")
    category: str = Field(..., description="Exercise category: 'strength', 'cardio', 'mobility', 'plyometric', etc.")
    equipment: list[str] = Field(default_factory=list, description="Equipment needed: ['barbell', 'rack', 'bench', etc.]")
    muscle_groups: Optional[list[str]] = Field(default=None, description="Target muscle groups: ['quadriceps', 'glutes', 'core', etc.]")
    movement_pattern: Optional[str] = Field(None, description="Movement pattern: 'squat', 'hinge', 'push', 'pull', 'carry', etc.")
    description: Optional[str] = Field(None, description="Description of how to perform the exercise")
    is_unilateral: bool = Field(default=False, description="Whether exercise is performed one side at a time")
    is_timed: bool = Field(default=False, description="Whether exercise is time-based rather than rep-based")
    session_exercise_details: SessionExerciseDetails = Field(..., description="Session-specific details for this exercise")


class WorkoutSession(BaseModel):
    """A single workout session within the plan."""
    session_name: str = Field(..., description="Name of the session, e.g. 'Workout A', 'Upper Body Day'")
    week_number: int = Field(..., ge=1, description="Which week this session belongs to")
    day_number: int = Field(..., ge=1, le=7, description="Day of the week (1=Monday, 7=Sunday)")
    session_order: int = Field(..., ge=1, description="Order of sessions in the plan")
    session_type: str = Field(..., description="Type: 'strength', 'cardio', 'hiit', 'mobility', 'recovery', etc.")
    exercises: list[SessionExercise] = Field(..., description="List of exercises in this session")


class StructuredWorkoutPlan(BaseModel):
    """Complete structured workout plan output from the LLM."""
    name: str = Field(..., description="Name of the workout plan")
    description: str = Field(..., description="Description of the plan and its goals")
    plan_type: str = Field(..., description="Type: 'strength', 'hypertrophy', 'endurance', 'weight_loss', 'general_fitness', etc.")
    duration_weeks: int = Field(..., ge=1, le=52, description="Duration of the plan in weeks")
    sessions: list[WorkoutSession] = Field(..., description="List of workout sessions in the plan")
